### ISSUE TITLE
Windows CE

### ISSUE THREAD

**Issue by 571x** [f1xpl/openauto#102]
I hope this "base" can also be used for in windows CE (6.0)?
Windows is mentioned in the support list.

**Comment by f1xpl** [comment]
Unfortunately, Windows CE is not supported.

**Comment by kylegordon** [comment]
CE 6 is a long dead platform, CE 7.0 is now only in extended support. 
@571x  If you *really* want Windows embedded support, I'd suggest looking at foreground UWP app for Windows IoT Core instead.

https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/buildingappsforiotcore

**Comment by 571x** [comment]
The radio's are Win 6.0 based, and can't be updated. The app EasyConnected is working as mirrorfunction for android but it isn't working properly :(
