### ISSUE TITLE
Does open-auto  work on raspberry zero?

### ISSUE THREAD

**Issue by akhilkathi97** [f1xpl/openauto#104]

**Comment by f1xpl** [comment]
Yes, it works.

**Comment by quattrofoto** [comment]
Yes, just got it working but it's taken me a couple of days to get it all working.  It's a bit slow to boot and load compared to a RPi 3 but it does all work now.  For now...

**Comment by dpnkrg** [comment]
@quattrofoto, Can you share the steps to us.
