### ISSUE TITLE
Weird audio problems

### ISSUE THREAD

**Issue by quattrofoto** [f1xpl/openauto#109]
Hi All,

I'm in the middle of setting up a RPi based Openauto system for my classic Land Rover, and I've hit a snag and it's driving me crazy.

I have the following:
RPi 3B
7" Touchscreen (not the official one)
Ugreen usb soundcard with mic input
Phone - Huawei P10plus running Oreo 
Openauto is running within fully up to date Raspbian Stretch.

Ok, I've got nearly everything up and running, I used Novaspirit's guide to install the software, everything seems to have gone fine.  The phone connects when plugged in.  The Android Auto is doing everything as it should, except for some strange issues with the audio.  I can use Google Assistant, she hears me, I hear her.  Navigation is audible, I have the BBC iPlayer Radio and that works fine.  The only thing that doesn't work as it should is music.  I am currently using Google Play Music, I can get the assistant to launch, play tracks etc, as well as using touch, the only problem is no sound is present.  The soundcard is working properly in Raspbian, audio is present with the other parts of Openauto, it's just the music that isn't working.  I sideloaded an XDA app that allowed me to use a non Android Auto music app to see if that worked, but that was the same (I have since uninstalled that app, uninstalled AA and also uninstalled the music app I tried, so none of that is causing any conflicts or other issues), and gone back to Google Play Music.  I've tried a few things I have found in various websites, I tried the guide on here about setting up Pulseaudio, none of it has made a difference.

I was using an old bluetooth speaker (but wired through the aux input, I'm not using bluetooth) but I switched to a pair of earphones as I'm short of space on my desk and it was easier and this has now highlighted another audio issue - it seems the mic is picking up ambient sound and playing that through the earphones at all times.  I haven't, as far as I am aware, done anything to cause this either?!

Anyway, apologies for the long post - I've tried to give as much info as I can to outline the issue sufficiently.  If any extra information is needed let me know, and thank you in advance for any and all help.
Regards,
Ste

**Comment by quattrofoto** [comment]
An update - I decided to have another look this morning, and weirdly the music is now coming through the speaker.  I haven't changed anything.  However only for some songs, others remain completely silent.  I can't see the file types on my phone but I know my collection on the phone (about 125GB's worth) are of various different formats.  Some are mp3's, others are .wma and I have a few .flac,  I'm guessing this is the issue?  Question is, what would be easiest, getting the pi to play the different codecs, or converting the many thousands of songs on my phone into .mp3?!

**Comment by f1xpl** [comment]
Decoding of the audio format is done by the phone. OpenAuto will receive raw PCM stream.

**Comment by quattrofoto** [comment]
That's what I thought - I believe all the computing power is provided by the phone, the pi is just displaying/playing what it's being passed.  I don't think it's anything to do with codecs either now, as it's definitely playing some .wma and .flac files without issue, and also not playing some .mp3 files.  I'm all out of ideas.  The phone itself has no issue at all with any of the files, they all play fine on their own, and inside my Ford via Bluetooth.  What could it be?

**Comment by f1xpl** [comment]
I think the best way would be to ask for support on Google Play Music or Android Auto helpdesk.

**Comment by quattrofoto** [comment]
Update - I had already reported the issue to the AA feedback/support and I didn't get anywhere, I was pointed to a thread where literally hundreds of people had a similar issue only they couldn't hear anything at all.  I could hear some songs, just not all and for no obvious reason, affected files were all different file types, there doesn't appear to be any reason to it.  Anyway, I did see one guy on that thread who fixed it by having an equalizer app installed.  He said any equalizer app will do it, so I installed one, but it didn't help.  I eventually found out that it is one particular app that cures it - Equalizer FX.  It has to be running in the background otherwise it won't help.  No idea how it fixes the issue or why, but the system is working now.

Thank you for the help, thank you for the awesome software too.

**Comment by azntklc** [comment]
Hey quattrofoto,

I have the same sound card as you do and I've been trying to set it up as my default sound output. I've been googling for the past few days and nothing has worked so far. The pi recognizes the sound card when plugged in (C-Media...). Rasp Ian stretch is up to date, I've tried changing ALSA config files, adding a new config file in /etc/modprobe.d like others have mentioned but these were old posts. Found another post somewhere and they mentioned something about removing pulseaudio but that's what this openauto is based on. Any ideas?

**Comment by quattrofoto** [comment]
I haven't had any issues with the sound card itself, and I haven't done anything special in regards to editing config files, I just used the right click context menu on the little speaker icon on the right hand side of the task bar.  You can try this: https://raspberrypi.stackexchange.com/questions/19705/usb-card-as-my-default-audio-device

The guy was having a similar problem, and it looks like they found a fix by the end.

**Comment by azntklc** [comment]
I know the sound card is good cuz it works on my other PC. I just tried the right click menu like u said and still nothing. Tried changing defaults still nothing. I'll do some more digging and see what i find. Thanks
