### ISSUE TITLE
Enable Browsing

### ISSUE THREAD

**Issue by Vitalic66** [f1xpl/openauto#11]
Do you think it is possible to enable browsing media from client side?

Or is it a server side problem (AA app on smartphone)?

AA is nice but this browsing problem sucks.

Is browsing disabled when sensors read wheel movement?

**Comment by szeater** [comment]
I'm *pretty* sure this is an AA app issue. Even when running standalone on the phone, once it starts picking up acceleration/rapid movement, it stops you from interacting with apps properly.

**Comment by f1xpl** [comment]
Browsing logic is handled in AA app. It looks like head unit has nothing to do with it.

**Comment by mbt28** [comment]
Hi,

Maybe it can be tricked by head unit with sending manuplated data but I beleive it is a good future to provide safer cruising.
