### ISSUE TITLE
Bash Build Script for Raspberry Pi 3

### ISSUE THREAD

**Issue by Curvin777** [f1xpl/openauto#110]
Possibly link on https://github.com/f1xpl/openauto/wiki/Build-instructions ?

Validated that it builds successfully against a fresh install of Raspbian Stretch With Desktop
https://downloads.raspberrypi.org/raspbian_latest (27Jun2018), fully updated to 06July2018.

-Chad

(Rename to OpenAutoInstall.sh, chmod 755)
[OpenAutoInstall.txt](https://github.com/f1xpl/openauto/files/2172481/OpenAutoInstall.txt)

**Comment by CluelessGenius** [comment]
not sure if related but im getting "unable to open mtp device" errors with my LG v30. you sure that script has everything neccessary?
