### ISSUE TITLE
App crashes after swiping up

### ISSUE THREAD

**Issue by newbiechi** [f1xpl/openauto#111]
Relative newbie - Everything seems fine on the RPi/OpenAuto end after connecting via usb.  OpenAuto detects the connection and the AndroidAuto screen is shown.  On the phone, AndroidAuto app launches but when I swipe up, the app crashes.

Has anyone experienced something similar?

**Comment by DGxInfinitY** [comment]
Yes actually. Your speaking about on the phone right?

**Comment by newbiechi** [comment]
Correct, on the phone. I checked the USB settings on the phone and set permissions on the Rpi, but still no dice.

**Comment by f1xpl** [comment]
If crash is related to the Android Auto app, I suppose that Android Auto helpdesk is better place to find support in investigation of the Android Auto app crash.

If you think that issue is related to the OpenAuto, please provide ADB logs.
