### ISSUE TITLE
Supported Layouts and Resolutions

### ISSUE THREAD

**Issue by mbt28** [f1xpl/openauto#12]
Hi,

What are supported layouts and resolutions of the Android Auto? I checked the source code out of curiosity there are options for different resolutions, and DPI s but I have no clue how flexible they are.

Regards,
Mehmet

**Comment by f1xpl** [comment]
What do you mean by Android Auto layouts?

**Comment by mbt28** [comment]
Hello,

Sorry for late reply. I mean for example 21:9 aspect ratio. Is it possible?

**Comment by f1xpl** [comment]
You can adjust screen DPI parameter in settings (video tab) to change the aspect ratio.

**Comment by sunne** [comment]
Hi, is it possible to change the max screen size somewhere? I have a small screen attached and I cannot get to see the whole window...
