### ISSUE TITLE
Touchscreen swap

### ISSUE THREAD

**Issue by Aygotori** [f1xpl/openauto#120]
Hello! 

Maybe someone here can help me to solve my problem...

I have openauto and kodi running at same time, openauto only shows up when the phone is plugged in and kodi come back when the phone is unplugged.  
I just add `@kodi` and `@/home/pi/openauto/bin/autoapp` to the file` ~/.config/lxsession/LXDE-pi/autostart`

Unfortunately, this way the touchscreen only works in kodi. I can't get him to work in openauto...
When i touch the screen the input is always made in kodi. 

Any idea how to switch the touchscreen input? 
(The touchscreen is a 7" Display from Adafruit with AR1100 microchip)

Big thanks @f1xpl for your great work!

**Comment by WarDrake** [comment]
Have you thought about handling it with a script?
open kodi automatically only, when you plug in a phone have a script close kodi, open openauto and close openauto and open kodi when when disconnecting it?

this seems to me to be the easiest way to handle it, there's a script on the wiki that does almost this exact same thing, just needs a bit of a modification

https://github.com/f1xpl/openauto/wiki/Shutdown-Raspberry-PI-3-when-phone-is-being-disconnecting
