### ISSUE TITLE
Google assistant popping noises

### ISSUE THREAD

**Issue by rosstadude** [f1xpl/openauto#121]
I have everything running just fine in my car. I love this project!!! 

There's only one problem. When I use the wake word, the audio response pops and cracks. If I say: OK Google, what's the weather today- the answer comes back with a significant amount of popping noise and crackling. 

However, I can listen to podcasts, navigation, pandora, google Play music, etc without any audio issues. 

I am using a RPi 3, with a ugreen USB Soundcard connected to the Aux jack of my Pioneer head unit and a mic plugged into that same sound card. Even if I unplug the Mic, the popping crackling noises persist in Google assistant. I have followed the suggestion on the wiki page for pulse audio, and this has not resolved it. I am using the RPi 7" touchscreen and a mauseberry circuit power supply. 

Oh, and my phone is the original Pixel XL running Android 8.1.0 with the July 5, security patch. 

Does anyone have an insight to offer? Thank you! 

EDIT: I have a bluetooth USB Dongle as well. I have followed the Wiki on how to enable that and paired my Pixel to the RPi. I disabled the speech and music channels in the Audio tab, Enabled Bluetooth and rebooted the Pi. The popping and crackling persists in Bluetooth audio between my Pixel and RPi

**Comment by rubenverhoef** [comment]
I have the same issue, also the Google maps navigation voice is giving popping noise. This voice is also out of sync when using for a while and sometimes stops in the middle of the sentence. And continues after a while. So after some time she is not saying the right things.

**Comment by kovmarci86** [comment]
Hi,
For me, this helped:
https://github.com/opencardev/crankshaft/issues/208

**Comment by rubenverhoef** [comment]
Switching to RT audio and that commit works for me also:)
