### ISSUE TITLE
Having trouble with performance on Intel

### ISSUE THREAD

**Issue by ftab** [f1xpl/openauto#122]
I built this on x86-64 Ubuntu 18.04 with Qt 5.11.1 and I don't know if I've done something wrong, but the video stream is extremely laggy and choppy (both 30 FPS and 60 FPS, any resolution).

Compared to the build instructions on the wiki, I added `CMAKE_PREFIX_PATH=/home/build/Qt/5.11.1/gcc_64/lib/cmake` and removed the Raspberry Pi build switch. I had to define that prefix path because the Qt 5.9 installation in Ubuntu did not contain one of the libraries needed (libqwayland-egl.so if I recall correctly)

On my dev workstation, I'm rocking a dual Xeon E5-2630v4 (20 cores total, 2.2-3.1 ghz) with Quadro NVS 310 and there doesn't appear to be any contention for CPU time while autoapp is running, it's just very very far behind the input (1-3 seconds, sometimes completely pausing until I click the mouse repeatedly, or wake the phone's screen) and the frame rate is not great. I've tried with 3 different Android phones - HTC One M9, LG G3, Moto Z... I have many switches I can flip in the BIOS, including isochronous memory access, early snoop, disabling SpeedStep, etc., none of which had an effect.

I've tried changing priority (`renice -n -20`), changing the audio from RT to Qt, I've also tried it on other computers
* Minnowboard Turbot quad core Atom 1.91ghz Ubuntu 18.04...for anyone playing along at home on 16.04, it didn't work due to outdated protobuf required by Qt 5.5/Unity conflicting with the 3.x version required by OpenAuto, so I had to upgrade. Ultimately, I got a black screen until I uninstalled gstreamer1.0-vaapi, so I guess for some reason hardware acceleration is a no go on Intel graphics?
Unfortunately, had a similar experience on 30 FPS - lagging significantly behind (2-3 seconds). At 60 FPS, I'd say half a second or so behind the touch input, and definitely not looking like 60 (looks more like 15). Wonder what it'd be like if I could get hardware acceleration working? Fun part is, sometimes the video screen comes up squished, taking only 1/4 of the display area (and touch input doesn't line up). I haven't figured out how to reliably reproduce - I can sometimes just go into settings and change the resolution back and forth and it'll work on the next connect O_o
* Lenovo W530 with Quadro K1000M. I had to switch to the X.Org X server Nouveau display driver, because the NVIDIA drivers were just coming up with a black screen. Again about half a second behind touch, and choppy animation.

On all three, I've tried generic kernel, lowlatency kernel, and setting cpu scaling from powersave to performance.

On the other hand, the last version of Crankshaft on an original non-OC Raspberry Pi 3 at least worked OK at 30 FPS (which is smoother than 60, oddly enough).

The touchscreen I'm using is a GeChic portable USB HID multitouch display w/ HDMI, polling at 100 Hz, in case that makes a difference (I would give my right arm to have 10ms or less touch latency, but that might be a pipe dream :p )

What else can I try to get it to be more responsive?

**Comment by f1xpl** [comment]
Ubuntu 18.04 does not need custom QT build and at least OpenAuto does not use anything related to the wayland. In my case it works with standard QT build from apt repositories.

Check video codecs, hardware acceleration and investigate why wayland is needed (it might be related to the problem as wayland is one of the screen composer lib).

Crankshaft uses OpenAuto as an Android Auto implementation. It does not add or improve any stuff related to the Android Auto handling.
