### ISSUE TITLE
Scaling up gui to physical screen size on larger screens

### ISSUE THREAD

**Issue by hawkeyexp** [f1xpl/openauto#124]
The gui depends on default rpi display res with 800x480. I noticed a lot of users which are using 1024x600 screens. In the case of different res the home gui is not shown full screen. Is there an easy way to scale up the gui to the real physical screen size ? I played arround but found no really working solution.
Any hint and idea would be nice :-)

**Comment by WarDrake** [comment]
Yeah, it's not complicated at all, what I did was fork this project and edited the main screen ui file to be 1024x600 and added my own background to it.
it's a pretty simple process, no programming required, it's just re arranging an xml file

**Comment by KLVN** [comment]
@WarDrake these lines? (https://github.com/f1xpl/openauto/blob/master/src/autoapp/UI/mainwindow.ui#L9)

**Comment by WarDrake** [comment]
Those are just the view size, so yes, but not only, The views are not responsive and every item on the screen has it's position defined by X and Y and width and height, so you have to edit those lines, plus the position of every item you want to move, it's a lot easier if you use a GUI, any qt view editor will work

**Comment by hawkeyexp** [comment]
I know - but this could not be the solution to create it for every esolution.

**Comment by WarDrake** [comment]
It isn't, to make a responsive GUI it'd have to coded and generated upon starting the app, instead of the simpler and easier to maintain xml view.

My comment simply addressed how to have a different resolution xml view.
