### ISSUE TITLE
No audio with pulseaudio on 3,5 mm jack

### ISSUE THREAD

**Issue by kom94** [f1xpl/openauto#126]
I have installed open auto on raspbian using a raspberry pi 3 B with the official 7" touchscreen.

I am trying to get audio out of the raspberry pi by a 3,5 mm jack on the raspberry pi, but i won't get any audio from open auto.
My audio works on Kodi using analog audio but when i switch to ALSA: .. pulseaudio i wont get any audio,
with a quick search i found out that open auto use pulseaudio so i tried to install it with success but still no audio by Open auto or Kodi, i have search for more try different things i bought an usb sound card but still no success.

can someone help me out, do i need an audio hat to get pulseaudio to work??

i want to install my raspberrypi in my car with a 2.1 system, i was thinking to connect the pi to the aux input on my radio.

![screenshot 2018-08-11 12 43 13](https://user-images.githubusercontent.com/3817869/43993602-480f7f34-9d90-11e8-9769-cdc9fe7e0538.png)
![screenshot 2018-08-11 17 16 47](https://user-images.githubusercontent.com/3817869/43993603-4823dc86-9d90-11e8-85cb-a3955b0aa170.png)
![screenshot 2018-08-11 17 23 29](https://user-images.githubusercontent.com/3817869/43993604-4837f748-9d90-11e8-96ed-7e5785b46d80.png)

**Comment by mentalinc** [comment]
Have you followed the two wiki posts?
You need a USB sound card...
https://github.com/f1xpl/openauto/wiki/Raspberry-PI-3-requirements

https://github.com/f1xpl/openauto/wiki/Pulseaudio-configuration

**Comment by kom94** [comment]
Well for some weird reason it works now!
i maked a file: "/etc/asound.conf" put in this code:

`pi@raspberrypi ~ $ cat ~/.asoundrc
pcm.!default {
        type hw
        card 0
        device 0
}
ctl.!default {
        type hw
        card 0
        device 0
}`

Got an error from kodi when i reboot the raspberry pi, so i removed the file en reboot again and it works it's just weird.
It works on kodi and open auto but not on the start video on raspbian but that's no big deal -_-

**Comment by MalteHillmann** [comment]
I have a similar problem:
I tested around with OpenAuto and the sound output works from the internal rpi3 3,5" jack. 
Now i bought an external USB-Soundcard. It works nice in VLC. But in OpenAuto it does not work. OpenAuto plays the sound always on the internal 3,5" jack of the rpi3.

**Comment by MalteHillmann** [comment]
I managed to set the output device by the name of the sound card.
Try this: https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_source
