### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by FredLL** [f1xpl/openauto#13]
Hi and Thank you for that great work,
I have a touch screen (Acer 22') plugged into the raspberry pi
touch is working when I launch autoapp (I can go to the settings and all).
but when I plug my phone, there's no reaction...
Any hint ?
Thanks
Fred

**Comment by f1xpl** [comment]
Hello,
did you enable touchscreen in settings (Input tab)?

**Comment by FredLL** [comment]
Now, I feel dumb ;-)
Thanks a lot, that did it.
