### ISSUE TITLE
Annimation Lagging and Freezing

### ISSUE THREAD

**Issue by swavans** [f1xpl/openauto#130]
I did the installation twice and experimented with various display and memory settings but whatever i do the animations seems to halt until clicked again. (switching tabs, opening menu;'s etc..)
When animations are disabled in deve menu the screen will stay black

**Comment by RcloP97** [comment]
Have you upgraded the gpu memory?

**Comment by swavans** [comment]
yes it was set too 256mb

**Comment by f1xpl** [comment]
Not reproducible.
