### ISSUE TITLE
Future of openauto opensource

### ISSUE THREAD

**Issue by rubenverhoef** [f1xpl/openauto#138]
Question, will the openauto opensource project still be updated with bug fixes and other stuff or is the project frozen?
Other question, when you buy openauto pro, can i get the source as well to edit stuff i want or is that not possible.

**Comment by f1xpl** [comment]
Open source version of OpenAuto is still alive and development is not closed in any way. Repository is open for the pull requests. All discovered bugs will be fixed as soon as possible. The same will be for the improvements.

The main difference between open source and the Pro version is that OpenAuto Pro focuses on the specific platform (currently Raspberry PI but there will be more in the future). Open source version remains as generic as possible. It will be handy for the developers which would like to build their own software based on the OpenAuto (Crankshaft is very good example here).

Also, OpenAuto Pro is licensed in different way than open source version so the source code is not public. Anyway, BlueWave is openeded for all the suggestions and ideas. If there are gaps in users expectations we surely consider to add new things to the backlog.

Taking the opportunity I would like to announce the new forum of the OpenAuto project at https://bluewavestudio.io/forum/. It will be definitely more convenient to discuss all the topics there.
