### ISSUE TITLE
Interactive screen over bluetooth

### ISSUE THREAD

**Issue by PaulBGD** [f1xpl/openauto#14]
Hello,

I'm unsure if it's because I have something setup wrong on my RPi3, however I'm not seeing the ability to show the interactive AndroidAuto app show up on my screen. I can play music to the RPi3 and control it with the AndroidAuto app, but it never shows up on the RPi3. It works fine over USB however.

**Comment by PaulBGD** [comment]
Maybe I could change this issue to showing some sort of "Now Playing" screen for Bluetooth devices?

**Comment by f1xpl** [comment]
Looks like not a scope of OpenAuto.
