### ISSUE TITLE
touch screen doesn't work at first time

### ISSUE THREAD

**Issue by computeridea** [f1xpl/openauto#142]
hi, i have a custom touchscreen, it works fine everywhere, in linux or in the waiting screen, but when i connect the phone, openauto start correctly, but  don't send information about the touch to the phone, if i try to plugin and plug out 2/3 times, it start to work.. 
so, i can use always the touch in openauto or raspian, it's just as the touch information doesn't arrive to the phone .
i tried with 2 phone, lg g4 and samsung a2 2017, same issues.. 
any advice please?

**Comment by ppatacchiola** [comment]
Same here, tried changing DPI and resolution in OpenAuto settings buttare doesn't fix the issue.
My setup: LCD waveshare 7" 
Oneplus 5 with Stock Android 9

**Comment by f1xpl** [comment]
Not reproducible.
