### ISSUE TITLE
Phone doesn't connect

### ISSUE THREAD

**Issue by ppatacchiola** [f1xpl/openauto#145]
It's been a week since my phone cant connect anymore to my raspberry, when i plug the usb into my phone i get this screen:  https://drive.google.com/file/d/1EblCV7s_y-VSyafPKQ9lB8d2vv76lQUP/view?usp=drivesdk

(Translation: comunication erorr n2)

Tried to reinstalling Android Auto app in my phone and resetting to default settings on OpenAuto settings page but that doesn't help.. 

Anyone had this issue before?

**Comment by Bobet21** [comment]
Same issue...I have upgraded my Androidauto version and since then i cannot connect anymmore

**Comment by ppatacchiola** [comment]
@bobet21 I fixed the problem by checking the option "allow unkown sources" in the developper settings of Android Auto app

**Comment by Bobet21** [comment]
Thanks, for me i needed to Connect to Bluetooth in addition to the USB cable

**Comment by Bishamon1987** [comment]
I just got the latest version of Android Auto from apkmirror.com, since its not officialy out in the Netherlands, but it doesnt seem to work.
So based on which version is this all based?

**Comment by abchet** [comment]
@ppatacchiola i fixed mine by https://github.com/f1xpl/openauto/wiki/udev-rules-(USB-permissions)
I don't know why but it fixed my issue
