### ISSUE TITLE
All pionner radios touch screen features doesn't work like changing route exiting buttons on side etc.

### ISSUE THREAD

**Issue by nameor123** [f1xpl/openauto#146]
I have a Pionner AVH-W4400nex. I use previous pionner radios and all of them are having problems with exiting out a route or change route or pressing the buttons on the side when I try to use the car radio's navigation screen I have a android note 9. Is this a android auto app that needs to be update or is it something else

**Comment by parkerlreed** [comment]
What does this have to do with OpenAuto? It sounds like you're using Android Auto on a headunit directly.
