### ISSUE TITLE
Callers hear themselves over BT

### ISSUE THREAD

**Issue by hodaddy4** [f1xpl/openauto#147]
Hello, I have the openauto pro 2.0 running and everything works great but I cant resolve the issue of callers hearing themselves when talking in the vehicle over bluetooth. I thought that's what the echo cancellation was supposed to take care of, and adjusting the Pulse Audio sound properties in Raspbian the input and outputs say "Echo Cancelled" but the mic still pics up the speakers (I assume) and the caller hears their own voice about a second later. I have tried adjusting the latency offset but it doesnt seem to change anything.

**Comment by chrisfromwa** [comment]
Did you get this fixed?  If not, since this is for OA-Pro,  you might have better luck with a response if you post this question in their forum
https://bluewavestudio.io/forum/viewforum.php?f
=10&sid=1417f58ad20dd90943597d4c5a83ccb0
