### ISSUE TITLE
Make fails when building openauto

### ISSUE THREAD

**Issue by lini500** [f1xpl/openauto#151]
WARNING: Noob present.

Make fails when building openauto.
Here my log:

```
pi@raspberrypi:~/openauto_build $ cmake -DCMAKE_BUILD_TYPE=Release -DRPI3_BUILD=TRUE -DAASDK_INCLUDE_DIRS="/home/pi/aasdk/include" -DAASDK_LIBRARIES="/home/pi/aasdk/lib/libaasdk.so" -DAASDK_PROTO_INCLUDE_DIRS="/home/pi/aasdk_build" -DAASDK_PROTO_LIBRARIES="/home/pi/aasdk/lib/libaasdk_proto.so" ../openauto
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   log
--   unit_test_framework
--   date_time
--   log_setup
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
-- Found rtaudio:
--  - Includes: /usr/include/rtaudio
--  - Libraries: /usr/lib/arm-linux-gnueabihf/librtaudio.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/openauto_build
pi@raspberrypi:~/openauto_build $ make
[  2%] Automatic moc, uic and rcc for target btservice
[  2%] Built target btservice_automoc
[ 14%] Built target btservice
[ 17%] Automatic moc, uic and rcc for target autoapp
Generating ui header ui_connectdialog.h
Segmentation fault
AUTOUIC: error: process for ui_connectdialog.h needed by
 "/home/pi/openauto/src/autoapp/UI/ConnectDialog.cpp"
failed:

uic failed...
CMakeFiles/autoapp_automoc.dir/build.make:57: die Regel für Ziel „CMakeFiles/autoapp_automoc“ scheiterte
make[2]: *** [CMakeFiles/autoapp_automoc] Fehler 1
CMakeFiles/Makefile2:173: die Regel für Ziel „CMakeFiles/autoapp_automoc.dir/all“ scheiterte
make[1]: *** [CMakeFiles/autoapp_automoc.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by Bishamon1987** [comment]
I got the same problems. The build makes some errors and after installing it just freezes at 26%

**Comment by Bobet21** [comment]
Have you downloaded the right branch ? using git to get openauto?

**Comment by Bishamon1987** [comment]
I used
git clone https://GitHub.com/f1xpl/openauto

Op vr 4 jan. 2019 11:47 schreef Louis <notifications@github.com:

**Comment by Bobet21** [comment]
Which specific error di you get?

**Comment by Bishamon1987** [comment]
When I try wifi connect. It almost never really connects. Tried it like 50
times and only 2 times it showed the phone screen. Rest of the time it just
stays in the connection screen.

With USB it shows error #2.

Op vr 4 jan. 2019 12:59 schreef Louis <notifications@github.com:

**Comment by Bobet21** [comment]
Well, this is completely different than the issue that is described, which is about building and running openauto....you hsould open another issue for this

**Comment by Bishamon1987** [comment]
Oooh, no I thought it was a different thread.
I used the build of GitHub.com/Novaspirit/androidauto_rpi_install


Op 4 jan. 2019 14:39 schreef "Louis" <notifications@github.com>:

Well, this is completely different than the issue that is described, which
is about building and running openauto....you hsould open another issue for
this

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/f1xpl/openauto/issues/151#issuecomment-451445958>, or mute
the thread
