### ISSUE TITLE
Stutters after a couple of hours

### ISSUE THREAD

**Issue by htruong** [f1xpl/openauto#17]
After playing music (Google Play Music) with OpenAuto for a couple of hours, the program seems to stutter a lot, and nothing would fix it other than restarting OpenAuto. Seems like there is a memory leak somewhere.

**Comment by f1xpl** [comment]
I tested it for more than 2 days of continous work several days and everything was okay. Seems like a problem with your PulseAudio or custom Qt compilation.

Please retest it with Qt multimedia from Raspbian's apt repository.
