### ISSUE TITLE
how to use 720 or 1080p

### ISSUE THREAD

**Issue by timmikefer** [f1xpl/openauto#173]
hey can you explain me how to use other resolution than 480p?
if I change to 720 or 1080p I am getting an error which says that the version of the phone and the version of android auto are not compatible @f1xpl

**Comment by parkerlreed** [comment]
Did you enable those resolutions in developer options (inside the Android Auto application)?

They aren't enabled by default.

**Comment by timmikefer** [comment]
Hey @parkerlreed. Thank you for your quick response :)

I have already heard about that but I dont know in which directory I can find this settings...

**Comment by Beebock** [comment]
https://www.makeuseof.com/tag/android-auto-tweaks/

**Comment by timmikefer** [comment]
Thank you very much!
