### ISSUE TITLE
Where is the "openauto_system.ini" mentioned in user manual?

### ISSUE THREAD

**Issue by cydia2020** [f1xpl/openauto#178]
Trying to figure out how to make the light sensor work here on my OAP

I cannot seem to find the said openauto_system.ini in the user manual

A hint to its directory would be nice

Cheers

Edit: Fix STT error

**Comment by parkerlreed** [comment]
If you have SSH/console

```
find / -name "openauto_system.ini"
```

**Comment by cydia2020** [comment]
Lol I just found it in ~, thanks anyway
