### ISSUE TITLE
Created basic install scripts for Arch Linux

### ISSUE THREAD

**Issue by parkerlreed** [f1xpl/openauto#19]
https://aur.archlinux.org/packages/aasdk-git/ 

https://aur.archlinux.org/packages/openauto-git/

aasdk (including the whole source folder) is copied into /opt/aasdk after building.

openauto build points to the /opt/aasdk in the cmake and also gets put in /opt/openauto

Shell script is placed at /usr/bin/autoapp which points to /opt/openauto/bin/autoapp

This makes testing at least on Arch dead simple at the moment. Hope it helps.

**Comment by f1xpl** [comment]
Added link to this issue on wiki page.
