### ISSUE TITLE
 f1x/aasdk/USB/USBWrapper.hpp: No such  file or directory

### ISSUE THREAD

**Issue by paulemurray** [f1xpl/openauto#22]
When running 'make' in openauto_build as the final step in building, I get the error in the title. I took a screenshot of the full error and attached it. 
![screenshot_20180228-224309](https://user-images.githubusercontent.com/36320737/36827450-30c33d08-1cd9-11e8-8dfa-c8cb78f57910.png)

**Comment by f1xpl** [comment]
You provided wrong path to aasdk and aasdk build dirs.
