### ISSUE TITLE
RPATH hardcoded in autoapp

### ISSUE THREAD

**Issue by parkerlreed** [f1xpl/openauto#36]
In cleaning up my Arch packages, I noticed there's an RPATH set in the autoapp executable

````
openauto-git E: Insecure RPATH '/build/openauto-git/src/openauto-git/lib' in file ('usr/bin/autoapp')
````

Is this needed for anything? It was suggested that this could be made available via a cmake flag in order to set it if need be.

**Comment by f1xpl** [comment]
In code there is no hardcoded paths. It looks like it is added by compiler/linker.
