### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by dev-danny** [f1xpl/openauto#4]
I've build the app following your instructions on the wiki, but unsure how to run it

Thanks

**Comment by f1xpl** [comment]
1. Open terminal
2. Navigate to openauto/bin
3. Execute ./autoapp
4. Connect your phone to the RPI via USB

**Comment by dev-danny** [comment]
Thank you, will give it ago in the morning:)

**Comment by f1xpl** [comment]
Issue clarified.

**Comment by kire73** [comment]
I've got this running on an RPi2, but connecting my phone to USB doesn't trigger the interface. Already running Android Auto on my Pixel XL when connecting it.

**Comment by f1xpl** [comment]
@kire73 Did you do also this step https://github.com/f1xpl/openauto/wiki/udev-rules-(USB-permissions) ?

**Comment by kire73** [comment]
@f1xpl Thank you, was just forgetting to run as root or sudo. Works great!
