### ISSUE TITLE
aasdk_build Make error

### ISSUE THREAD

**Issue by x3graphics** [f1xpl/openauto#43]
Getting this error on the make command for aasdk

pi@AUTOPI:~/aasdk_build $ make
[  0%] Running C++ protocol buffer compiler on /home/pi/aasdk/aasdk_proto/VideoResolutionEnum.proto
VideoResolutionEnum.proto:19:8: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
aasdk_proto/CMakeFiles/aasdk_proto.dir/build.make:822: recipe for target 'aasdk_proto/VideoResolutionEnum.pb.cc' failed
make[2]: *** [aasdk_proto/VideoResolutionEnum.pb.cc] Error 1
CMakeFiles/Makefile2:122: recipe for target 'aasdk_proto/CMakeFiles/aasdk_proto.dir/all' failed
make[1]: *** [aasdk_proto/CMakeFiles/aasdk_proto.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by f1xpl** [comment]
Please use newer version of protobuf compiler.

**Comment by x3graphics** [comment]
I was installing on jessie, my bad
