### ISSUE TITLE
Bluetooth audio from phone 

### ISSUE THREAD

**Issue by kgill98** [f1xpl/openauto#47]
I'm looking to have the music and gps audio run through my phone like the calls do. As I have my phone connect via Bluetooth to my car. This would mean that the audio wouldn't go through the pi. Is this possible? What files would I need to re configure and how ?

**Comment by f1xpl** [comment]
Go to settings -> audio tab and uncheck Media channel and Speech channel.

**Comment by kgill98** [comment]
Perfect that worked! Is there also a way I can get my ok Google to use my phone's mic as I am not planning on setting up a mic on my pi. When I say ok Google it will open up but won't here me speak after. 

Thanks in advance
