### ISSUE TITLE
"Show touches" or "Pointer location"

### ISSUE THREAD

**Issue by xstsx** [f1xpl/openauto#48]
Hi,
Is it possible to add this features for debug purposes?

I have an issue with touch screen, it's working fine in xorg. But at AA screen it's get some kind of offset or scalling multiplier. Trying to overide it with xinput.
My setup is RaspberryPI3 + 7" LCD + multitouch screen

**Comment by jayanty** [comment]
Did you try enabling the mouse pointer with the button that enables the mouse pointer?

**Comment by xstsx** [comment]
I have, no mouse pointer at any layer of OMX.

**Comment by f1xpl** [comment]
What desktop driver do you use?

**Comment by xstsx** [comment]
What do you mean ? Drivers of what ?
