### ISSUE TITLE
Running openauto without xorg

### ISSUE THREAD

**Issue by xstsx** [f1xpl/openauto#49]
Hi,
Is there an option to run openauto without running xorg?

**Comment by xstsx** [comment]
Sorry, I didn't mention it.
Yes ,I'm using Raspberry PI3 and when I trying to run autoapp it says "Display not found". So it's looking for display of Xorg I believe.
How I'm pointing it to use omx without Xorg? Or recompile qt5-base with -opengl es is the only option ?

My system:
Raspberry PI3
LCD 7" HDMI + multitouch
Archlinux

**Comment by parkerlreed** [comment]
Yes you have to rebuild Qt. See here. https://github.com/htruong/crankshaft/wiki/Building-the-binary-blobs

**Comment by f1xpl** [comment]
Issue is not related to the OpenAuto. In case of dev discussion please join gitter chat.
