### ISSUE TITLE
Communication Error 2

### ISSUE THREAD

**Issue by danbiba** [f1xpl/openauto#56]
Android Auto on my Raspberry pi is saying Waiting for Device, but the phone is saying "Android Auto encountered an error  Communication error 2 - the phone and the car are running incompatible software"  this happens on an older android LG and my newer Moto Z Play Droid. Any ideas?

**Comment by majt3** [comment]
I had a similar issue today.  This turned out to be that I was trying to run the emulator at 1080p but hadn't enabled that resolution in the developer settings of the Android Auto app on the phone.

**Comment by f1xpl** [comment]
What is your setup? Do you have USB sound card connected? Please provide more details.

**Comment by majt3** [comment]
In my case I am using a Pi 3 with additional hardware except a keyboard, mouse and 1080p display.
