### ISSUE TITLE
openauto freezes if connected wireless and loses wifi

### ISSUE THREAD

**Issue by WarDrake** [f1xpl/openauto#58]
If the wireless connection is lost (walk away and take the phone after done driving) while openauto is connected wirelessly the application freezes and all input is disregarded, be it mouse/keyboard/touch

can't connect trough ssh anymore either, but if you stay within range for a couple minutes the system connects back to the wifi, however openauto stays frozen and the system not responsive.

**Comment by f1xpl** [comment]
Looks like the problem is related to the TCP keep alive mechanism.

**Comment by f1xpl** [comment]
Correction has been merged to the development branch. OpenAuto will close connection after ~10 seconds when broken link has been detected. In order to test it please clone and compile latest development branch of aasdk and openauto projects.

**Comment by WarDrake** [comment]
I checked out and compiled both Development versions, Fix works as intended, after a few seconds of the wifi being lost, openauto now returns to the connection screen and doesn't freeze anymore.

**Comment by f1xpl** [comment]
Merged to master.
