### ISSUE TITLE
Udev rules improvement

### ISSUE THREAD

**Issue by WarDrake** [f1xpl/openauto#59]
There are udev rules for android that are kept up to date and are not as open as the general one on the wiki right now

snowdream is the maintainer and he has his own github project with this
https://github.com/snowdream/51-android

easiest way to install the rules is this : 
sudo wget -P /etc/udev/rules.d https://raw.githubusercontent.com/snowdream/51-android/master/51-android.rules

**Comment by f1xpl** [comment]
Thanks. I updated wiki [page](https://github.com/f1xpl/openauto/wiki/udev-rules-(USB-permissions)
