### ISSUE TITLE
Clean shutdown

### ISSUE THREAD

**Issue by akileos** [f1xpl/openauto#6]
Hello,

 Have you yet been able to take care of clean shutdowns with car turning off ?

Thanks

**Comment by aledthom** [comment]
Think you'll need to do that with external hardware, there's various DIY solutions as well as commercially available hats for that exact purpose

**Comment by Vitalic66** [comment]
Right, i use pibus for BMW as powersupply, sound DAC and Ibus communicator. Pi shuts down when pibus received command via Ibus from car.

**Comment by aledthom** [comment]
I just wired mine to the battery live, with a gpio sensing the ignition live for shutdown and startup

**Comment by f1xpl** [comment]
It looks like issue is not related directly to the openauto. Please reopen in case of any doubts.
