### ISSUE TITLE
2018-03-13-raspbian-stretch compile fails (could not find rtAudio)

### ISSUE THREAD

**Issue by prbs57** [f1xpl/openauto#66]
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   log
--   unit_test_framework
--   date_time
--   log_setup
--   filesystem
--   thread
--   regex
--   chrono
--   atomic
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
CMake Error at cmake_modules/Findrtaudio.cmake:64 (message):
  Could not find rtaudio
Call Stack (most recent call first):
  CMakeLists.txt:35 (find_package)

=======
$ sudo apt-get install librtaudio-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  erlang-base erlang-crypto erlang-syntax-tools fonts-lato libqt5scintilla2-12v5 libqt5scintilla2-l10n libqt5x11extras5 libqwt-qt5-6
  libruby2.3 libscsynth1 libsctp1 libyaml-0-2 rake ruby ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert
  ruby-test-unit ruby2.3 rubygems-integration
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  jackd1 libasound2-dev libglib2.0-dev libjack-dev libjack0 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpulse-dev libpulse-mainloop-glib0
  librtaudio5a libzita-alsa-pcmi0 libzita-resampler1 uuid-dev
Suggested packages:
  jack-tools meterbridge libasound2-doc libglib2.0-doc librtmidi-dev
Recommended packages:
  qjackctl
The following packages will be REMOVED:
  jackd jackd2 libjack-jackd2-0 qjackctl sonic-pi supercollider-server
The following NEW packages will be installed:
  jackd1 libasound2-dev libglib2.0-dev libjack-dev libjack0 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpulse-dev libpulse-mainloop-glib0
  librtaudio-dev librtaudio5a libzita-alsa-pcmi0 libzita-resampler1 uuid-dev
0 upgraded, 15 newly installed, 6 to remove and 2 not upgraded.
Need to get 0 B/4,787 kB of archives.
After this operation, 8,979 kB of additional disk space will be used.
Do you want to continue? [Y/n] Preconfiguring packages ...
y
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'libopenmpi2:armhf' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)
pi@raspberrypi:~/androidauto_rpi_install $

**Comment by f1xpl** [comment]
Something is wrong with your packet manager. Try to:

>$ sudo apt-get update
>$ sudo apt-get install librtaudio-dev librtaudio5a

**Comment by prbs57** [comment]
This is the 5th iteration of fresh install, update, upgrade and
./install.sh.

**Comment by f1xpl** [comment]
What is install.sh script?

**Comment by prbs57** [comment]
https://github.com/novaspirit/androidauto_rpi_install/blob/master/install.sh

I'v also tried the command individually but get stuck at the same error:
`$ sudo apt-get install librtaudio-dev librtaudio5a`

**Comment by f1xpl** [comment]
I think the best way would be to google this error

dpkg: unrecoverable fatal error, aborting:
files list file for package 'libopenmpi2:armhf' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)
pi@raspberrypi:~/androidauto_rpi_install $

and try to find a solution. Issue is not related to the OpenAuto at all.

**Comment by prbs57** [comment]
Yep. I tried. Nothing helpful out there. Posting here in case anyone else
runs into this during openauto installation. Will keep looking.

Thanks!

**Comment by DGxInfinitY** [comment]
Same issue here.

**Comment by ganey** [comment]
Hmm, I built fine yesterday on a pi3+, was a completely new setup. 

I didn't get any errors but I also think sound isn't working..

**Comment by DGxInfinitY** [comment]
So far I haven't been able to get past this. I wonder if we have to use an older image of rasbian with a working package manager.

**Comment by f1xpl** [comment]
I installed latest raspbian stretch desktop image (2018-03-13) and compiled aasdk and openauto without any issues.

It looks like you have messed your raspbian instance. Try to write fresh image to the sd card once again. Then run it and do:

> $ sudo apt-get update
> $ sudo apt-get upgrade
> $ sudo apt-get update

 and then follow build instructions for aasdk and openauto carefully.
