### ISSUE TITLE
Got stuck on final step of the build

### ISSUE THREAD

**Issue by whitetiger430** [f1xpl/openauto#71]
Hi

Just the last step, to type make in the openauto_build directory.. thought it was gonna be easy but the following came up

I tried changing the directory in the App.cpp, but doesn't make a difference.

Thanks for the help 

` pi@BZ-HUD:~/openauto_build $ make
[  2%] Automatic moc, uic and rcc for target btservice
[  2%] Built target btservice_automoc
[ 14%] Built target btservice
[ 17%] Automatic moc, uic and rcc for target autoapp
[ 17%] Built target autoapp_automoc
Scanning dependencies of target autoapp
[ 19%] Building CXX object CMakeFiles/autoapp.dir/src/autoapp/App.cpp.o
/home/pi/openauto/src/autoapp/App.cpp:20:62: fatal error:
home/pi/aasdk/include/f1x/aasdk/USB/AOAPDevice.hpp: No such file or
directory
 #include <home/pi/aasdk/include/f1x/aasdk/USB/AOAPDevice.hpp>
                                                              ^
compilation terminated.
CMakeFiles/autoapp.dir/build.make:62: recipe for target
'CMakeFiles/autoapp.dir/src/autoapp/App.cpp.o' failed
make[2]: *** [CMakeFiles/autoapp.dir/src/autoapp/App.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/autoapp.dir/all' failed
make[1]: *** [CMakeFiles/autoapp.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by f1xpl** [comment]
You provided worng path to aasdk or did not clone it in home directory.
