### ISSUE TITLE
Running OpenAuto without xserver

### ISSUE THREAD

**Issue by Daniele9575** [f1xpl/openauto#72]
Hi,
I didn't understand if it is possible to run OpenAuto without having an xserver installed, and if it is how can i configure OpenAuto to run without x?

Thanks for the help.

**Comment by f1xpl** [comment]
It is not officialy supported but should be possible.

**Comment by poxin13** [comment]
Not 100% what you were asking for, still requires xorg installed, but managed to get it launched with booting direct to CLI, bypassing the desktop.

`sudo xinit /home/pi/openauto/bin/autoapp $* -- :0` I suppose `startx /home/pi/openauto/bin/autoapp` would also work.

Boot time to openauto does seem faster this method without booting the full desktop. Unfortunately plugging in the phone doesn't update the screen and causes touch to not work untill unplugged again.

**Comment by xstsx** [comment]
The only way I know, it's recompile qt5 without xorg support and with eglfs support for raspberry pi.
