### ISSUE TITLE
HFP Sound Quality

### ISSUE THREAD

**Issue by poxin13** [f1xpl/openauto#74]
Attempting to troubleshoot an issue with the sound quality using bluetooth HFP setup.

If i record direct using the USB Mic: `arecord --format S16_LE --rate 16000 -c1 test.wav` it sounds good.

However if I make a call and leave a voicemail to listen back, the call quality is *really* bad, lots of static, etc. It is using the USB mic for input fine.

OFono and the routing seem to be working no problems. Have tired with and without the echo/noise reduction in default.pa, no difference. A2DP also no issues.

**Comment by f1xpl** [comment]
Hello,
HFP is not a scope of OpenAuto. Try to explore OFono and Pulseaudio forums to find a solution.
