### ISSUE TITLE
It doesn't show anything with vnc viewer

### ISSUE THREAD

**Issue by piposlink** [f1xpl/openauto#77]
I can't use openauto when I have VNC Viewer working it doesn't show the screens but works great because when I tap the phone call my friends.
I only want to prove it because I don't have a raspberry screen I realy want to know how can I use it with VNC Viewer

**Comment by f1xpl** [comment]
Using OpenAuto via VNC is not supported.

**Comment by jacobholes** [comment]
Sorry for commenting on a closed issue, but I was able to get OpenAuto visible with RealVNC by going into VNC Options, then the Troubleshooting, then checking enable experimental direct capture mode. It's very laggy so YMMV.

**Comment by piposlink** [comment]
Thank you @f1xpl  and @jacobholes  
I used to have that doubt
