### ISSUE TITLE
[feature request] Separate volume control navigation voice/music

### ISSUE THREAD

**Issue by rubenverhoef** [f1xpl/openauto#79]
I would like to have independent volume control of the navigation voice and my music. Could this be possible? So i can set a "fixed" volume for my navigation voice, and when i turn the volume up for my music the lovely voice of my navigation will not scream at me.

**Comment by f1xpl** [comment]
You should use your system settings in order to control volume level.

**Comment by rubenverhoef** [comment]
Can I control the AA navigation voice volume independent of the AA media volume in the system settings?? Don't think so?

**Comment by f1xpl** [comment]
In pavucontrol you will see 3 separated output channels (media, speech and system). You can set volume of those channels independently.
