### ISSUE TITLE
Recieving or makeing a call on AA; the audio call only can be heart by the speaker of the phone

### ISSUE THREAD

**Issue by RcloP97** [f1xpl/openauto#81]
While the music and other stuff is send to the speaker connected to Raspberry, during the call is not and just can be heard by the phone; any solution? Maybe there's some configuration i have to do?  (btw the microphone which is working during the call is the one connected to rasbperry)

**Comment by f1xpl** [comment]
This is normal behavior of AA. You must configure and connect to HFP bluetooth profile.

**Comment by RcloP97** [comment]
@f1xpl so, setting up the oFono, connecting my phone through bt and then i should try to execute AA by bt? I remember one time I tried to execute AA through usb while my phone where paired with bt; did not work and then the AA was not working anymore (even just plugging it with just usb)
