### ISSUE TITLE
Keyboard Question

### ISSUE THREAD

**Issue by rebeccagodfrey** [f1xpl/openauto#87]
I have OpenAuto running on a RPI3B in my car with a 7" touch screen and all has been going well so far. I noticed Keyboard bindings mentioned in the Wiki. I have connected a usb keyboard to my RPI but there doesn't seam to be any response in OpenAuto. I can see the keyboard works in the os (Raspian Stretch). Should the keyboard be connected to the RPI or the phone? Is there something else I need to do to get it working?  Thanks

**Comment by f1xpl** [comment]
You must enable desired keys in settings.
