### ISSUE TITLE
Quit OpenAuto app not available

### ISSUE THREAD

**Issue by Sonnet71** [f1xpl/openauto#90]
Thanks for the building instructions and the given USB rules. All went well and OpenAuto is up and running. But I found no way to minimize this app to use all the other functionalities of the basic Raspian system. It just stays in fullscreen mode until the phone is unconnected.

When pressing the button in the low right corner I just get a new screen with a large button named with "Return to OpenAuto" but no other option

Will the minimize or quit functionality without unplugging the phone be implemented in the future?

**Comment by f1xpl** [comment]
https://github.com/f1xpl/openauto/issues/33

**Comment by f1xpl** [comment]
Mentioned functionalities are part of OpenAuto Pro (new project that I am involved in). Take a look at the https://www.youtube.com/watch?v=9sTOMI1qTiA to see if this is something you are looking for.
