### ISSUE TITLE
Rendering AA contents on portion of the display

### ISSUE THREAD

**Issue by amijoe2001** [f1xpl/openauto#96]
Thank you for this app. I got this working on my RPi3 with Adafruit HDMI display. It did not work initially because I was powering up display from RPi USB port. It worked after I powered display from a wall charger .

I will like to customize the display size. I mean I want to allow AA rendered on only a portion of the available display size. (e.g. upper half display AA and bottom half displays native RPi contents. Is it possible to achieve?

**Comment by f1xpl** [comment]
You can dig into https://github.com/f1xpl/openauto/blob/development/src/autoapp/Projection/OMXVideoOutput.cpp code to find a way to adjust display region.Also adjustment of scalling the touch input coords will be needed,

**Comment by dmarman** [comment]
@amijoe2001 I am interested in doing something similar. Did you dig deeper into this topic?
